### ISSUE TITLE
Add more curation types to filtering.

### ISSUE THREAD

**Issue by dblodorn** [public-assembly/curation-interactions#26]
- [ ] NFT contract - 4 (has token id)  - #4
- [ ] Drops "generative" contract - has tokenid - #6
- [ ] NFT contract without token id - #1

basically refactoring this:
https://github.com/public-assembly/curation-interactions/blob/main/packages/interactions/src/hooks/useGetEditionsListings.tsx

Adding fetching strategies for each value.
